## Phase 1: Predicting Drug resistance (y = Drugs, X = Mutations)

In [58]:
#Import packages
import pandas as pd

#Read in data
df = pd.read_csv("geno-pheno.dataset.tsv", sep = "\t")

df.head()

/tmp/ipykernel_8898/2676976629.py:5: DtypeWarning: Columns (0: AZT, 1: DDCFoldMatch, 2: TAFFoldMatch) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("geno-pheno.dataset.tsv", sep = "\t")

,RefID,IsolateID,IsolateName,Species,Type,PtID,Method,3TC,3TCFoldMatch,ABC,...,P291,P292,P293,P294,P295,P296,P297,P298,P299,P300
0,756,9918,CA9918,HIV1,Clinical,1391.0,PhenoSense,200.0,>,4.6,...,-,-,-,-,-,-,-,-,-,-
1,756,3832,CA3832,HIV1,Clinical,1433.0,PhenoSense,200.0,>,8.8,...,-,-,.,.,.,.,.,.,.,.
2,756,10464,CA10464,HIV1,Clinical,634.0,PhenoSense,200.0,>,14.0,...,.,.,.,.,.,.,.,.,.,.
3,756,9928,CA9928,HIV1,Clinical,637.0,PhenoSense,200.0,>,6.7,...,-,-,V,-,-,-,K,-,-,-
4,756,4372,CA4372,HIV1,Clinical,1274.0,PhenoSense,200.0,>,7.1,...,-,-,V,-,-,-,-,-,-,-

In [64]:
##Cleaning the data set
df2 = df.copy()
df2.head()

,RefID,IsolateID,IsolateName,Species,Type,PtID,Method,3TC,3TCFoldMatch,ABC,...,P291,P292,P293,P294,P295,P296,P297,P298,P299,P300
0,756,9918,CA9918,HIV1,Clinical,1391.0,PhenoSense,200.0,>,4.6,...,-,-,-,-,-,-,-,-,-,-
1,756,3832,CA3832,HIV1,Clinical,1433.0,PhenoSense,200.0,>,8.8,...,-,-,.,.,.,.,.,.,.,.
2,756,10464,CA10464,HIV1,Clinical,634.0,PhenoSense,200.0,>,14.0,...,.,.,.,.,.,.,.,.,.,.
3,756,9928,CA9928,HIV1,Clinical,637.0,PhenoSense,200.0,>,6.7,...,-,-,V,-,-,-,K,-,-,-
4,756,4372,CA4372,HIV1,Clinical,1274.0,PhenoSense,200.0,>,7.1,...,-,-,V,-,-,-,-,-,-,-

In [65]:
# Dimensionality of data
df2.shape

(2505, 335)

### Exploratory data analysis

In [66]:
#DRop columns we don't need in the training
df2 = df.drop(columns = ["RefID","Species","Type", "Method", "NNRTIDRMs", 'CompleteMutationListAvailable', 'Author','NonDRMs', 'Author','RefYear', 'MedlineID', 'Title',  'PtID'])
df2.head(n = 300)

#Remove Protease positions

df2 = df2.loc[:, ~df2.columns.str.match(r"^P\d+$")]
df2.head()
df2.shape

(2505, 23)

In [67]:
# Explore the data
#df2.describe()

#df2.info()

df2.columns

df2.shape

(2505, 23)

In [68]:
# Find reverse transcriptase columns
[col for col in df2.columns if "RT" in col.upper()]

['NRTIDRMs']

In [69]:
#Check which columns retained
df2.columns

Index(['IsolateID', 'IsolateName', '3TC', '3TCFoldMatch', 'ABC',
       'ABCFoldMatch', 'AZT', 'AZTFoldMatch', 'D4T', 'D4TFoldMatch', 'DDC',
       'DDCFoldMatch', 'DDI', 'DDIFoldMatch', 'FTC', 'FTCFoldMatch', 'ISL',
       'ISLFoldMatch', 'TAF', 'TAFFoldMatch', 'TDF', 'TDFFoldMatch',
       'NRTIDRMs'],
      dtype='str')

In [70]:
#View data 
df2.head()

,IsolateID,IsolateName,3TC,3TCFoldMatch,ABC,ABCFoldMatch,AZT,AZTFoldMatch,D4T,D4TFoldMatch,...,DDIFoldMatch,FTC,FTCFoldMatch,ISL,ISLFoldMatch,TAF,TAFFoldMatch,TDF,TDFFoldMatch,NRTIDRMs
0,9918,CA9918,200.0,>,4.6,=,0.6,=,1.0,=,...,=,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M184V
1,3832,CA3832,200.0,>,8.8,=,3.2,=,1.9,=,...,=,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"M41L, L74LV, M184V, L210W, T215Y"
2,10464,CA10464,200.0,>,14.0,=,307,=,6.4,=,...,=,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"M41L, E44A, D67N, T69D, M184V, L210W, T215Y"
3,9928,CA9928,200.0,>,6.7,=,6.5,=,1.6,=,...,=,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"M41L, M184V, T215Y"
4,4372,CA4372,200.0,>,7.1,=,0.8,=,1.3,=,...,=,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"D67N, K70G, M184V, T215F, K219Q"

In [71]:
#Identifying unique mutations in the dataset

df2.dtypes

IsolateID         int64
IsolateName         str
3TC             float64
3TCFoldMatch        str
ABC             float64
ABCFoldMatch        str
AZT              object
AZTFoldMatch        str
D4T             float64
D4TFoldMatch        str
DDC             float64
DDCFoldMatch        str
DDI             float64
DDIFoldMatch        str
FTC             float64
FTCFoldMatch        str
ISL             float64
ISLFoldMatch        str
TAF             float64
TAFFoldMatch        str
TDF             float64
TDFFoldMatch        str
NRTIDRMs            str
dtype: object

In [72]:
# Number of duplicate IsolateIDs
print("Duplicate IsolateIDs:", df2["IsolateID"].duplicated().sum())

Duplicate IsolateIDs: 0

In [73]:
# Abstract drugs
missing = (df2.isnull().sum().to_frame(name="Missing"))

missing["Percent"] = round(missing["Missing"] / len(df_clean) * 100, 2)

missing.sort_values("Percent", ascending=False)

              Missing  Percent
ISLFoldMatch     2473    98.72
ISL              2473    98.72
TAFFoldMatch     2409    96.17
TAF              2409    96.17
DDCFoldMatch     2036    81.28
DDC              2003    79.96
FTCFoldMatch     1948    77.76
FTC              1948    77.76
NRTIDRMs          512    20.44
TDF               493    19.68
TDFFoldMatch      493    19.68
ABCFoldMatch      308    12.30
ABC               274    10.94
3TCFoldMatch      176     7.03
D4TFoldMatch      162     6.47
DDIFoldMatch      162     6.47
AZTFoldMatch      158     6.31
3TC               146     5.83
D4T               128     5.11
DDI               128     5.11
AZT               124     4.95
IsolateName         0     0.00
IsolateID           0     0.00

In [74]:
#Measure completeness of Drug data
drug_cols = ["3TC", "ABC", "AZT", "D4T", "DDC", "DDI", "FTC", "ISL", "TAF", "TDF"]

available = df2[drug_cols].notna().sum().sort_values(ascending=False)

print(available)

AZT    2381
D4T    2377
DDI    2377
3TC    2359
ABC    2231
TDF    2012
FTC     557
DDC     502
TAF      96
ISL      32
dtype: int64

In [76]:
#DRop columns we don't need in the training
df_clean = df2.drop(columns = ["3TCFoldMatch", "ABCFoldMatch", "AZTFoldMatch", "D4TFoldMatch", "DDCFoldMatch", "DDIFoldMatch", "FTCFoldMatch", "ISLFoldMatch", "TAFFoldMatch", "TDFFoldMatch"])
df_clean.head(n = 300)

#Drop DRugs with < 1000 complete cells
df_clean = df_clean.drop(columns = ["DDC", "FTC", "ISL", "TAF"])
df_clean.head(n=30)

,IsolateID,IsolateName,3TC,ABC,AZT,D4T,DDI,TDF,NRTIDRMs
0,9918,CA9918,200.0,4.6,0.6,1.0,1.6,NaN,M184V
1,3832,CA3832,200.0,8.8,3.2,1.9,2.1,NaN,"M41L, L74LV, M184V, L210W, T215Y"
2,10464,CA10464,200.0,14.0,307,6.4,2.7,NaN,"M41L, E44A, D67N, T69D, M184V, L210W, T215Y"
3,9928,CA9928,200.0,6.7,6.5,1.6,1.4,NaN,"M41L, M184V, T215Y"
4,4372,CA4372,200.0,7.1,0.8,1.3,1.9,NaN,"D67N, K70G, M184V, T215F, K219Q"
5,4391,CA4391,200.0,5.9,1.9,1.3,1.7,NaN,"D67N, K70R, M184V, K219Q"
6,9912,CA9912,200.0,18.0,100,11.0,3.5,NaN,"E40F, M41L, D67N, V75M, M184V, L210W, T215Y, K..."
7,9945,CA9945,200.0,29.0,726,10.0,4.1,NaN,"M41L, D67N, T69D, K70R, V75M, M184V, T215F, K219W"
8,9916,CA9916,200.0,7.7,7.9,2.3,1.8,NaN,"D67N, K70R, M184V, K219Q"
9,9944,CA9944,200.0,8.5,14,1.7,1.7,NaN,"M41L, M184V, L210W, T215Y"
10,3871,CA3871,200.0,8.1,4.7,1.8,1.7,NaN,"M41L, L74V, M184V, L210W, T215Y"
11,10474,CA10474,200.0,8.6,10,1.7,1.9,NaN,"M41L, M184V, T215Y"
12,9919,CA9919,200.0,20.0,228,11.0,20.0,NaN,"A62V, S68G, K70G, V75I, F77L, Y115F, F116Y, Q1..."
13,2633,CA2633,200.0,4.3,3.9,1.4,1.2,NaN,"M41L, M184V, L210W, T215Y"
14,9435,CA9435,200.0,9.6,35,3.3,2.1,NaN,"M41L, E44D, D67N, T69D, M184V, L210W, T215Y"
15,10470,CA10470,4.1,3.5,22,3.2,1.4,NaN,"M41L, E44D, D67N, K70R, L74I, L210W, K219E"
16,10499,CA10499,4.6,6.7,340,3.0,1.8,NaN,"M41L, D67N, K70R, T215Y, K219Q"
17,9949,41731906,200.0,4.8,0.5,0.8,1.5,NaN,M184V
18,10465,CA10465,200.0,7.7,4.4,1.7,1.5,NaN,"M41L, E44D, M184V, L210W, T215Y"
19,9915,CA9915,200.0,9.9,100,3.9,2.1,NaN,"M41L, E44D, D67N, M184V, L210W, T215Y, K219N"
20,11265,SD-5,NaN,4.0,NaN,1.0,NaN,NaN,M184V
21,11251,SD-16,NaN,1.0,NaN,NaN,NaN,NaN,K70R
22,11255,SD-13,NaN,5.0,NaN,NaN,NaN,NaN,"M41L, S68SG, M184V, L210W, T215Y"
23,11247,SD-18,NaN,2.0,NaN,NaN,NaN,NaN,"D67N, K70R, M184V, K219Q"
24,11261,SD-7,NaN,5.0,NaN,NaN,NaN,NaN,"L74V, M184V"
25,11259,SD-10,NaN,3.0,NaN,1.0,NaN,NaN,M184V
26,11243,SD-20,NaN,4.0,NaN,NaN,NaN,NaN,"M41L, M184V, T215Y"
27,11263,SD-6,NaN,4.0,NaN,NaN,NaN,NaN,"D67G, S68G, K70R, M184V, K219Q"
28,11267,SD-2,NaN,7.0,NaN,2.7,NaN,NaN,"M41L, M184V, L210W, T215Y"
29,11253,SD-14,NaN,5.0,NaN,NaN,NaN,NaN,"M41L, L74I, M184V, L210W, T215Y"

In [77]:
#Data types for df_clean
print(df_clean.dtypes)

IsolateID        int64
IsolateName        str
3TC            float64
ABC            float64
AZT             object
D4T            float64
DDI            float64
TDF            float64
NRTIDRMs           str
dtype: object

In [79]:
#Save cleaned data 
df_clean.to_csv("geno-pheno_clean.tsv", sep="\t", index=False)
df_clean.head(n=30)

,IsolateID,IsolateName,3TC,ABC,AZT,D4T,DDI,TDF,NRTIDRMs
0,9918,CA9918,200.0,4.6,0.6,1.0,1.6,NaN,M184V
1,3832,CA3832,200.0,8.8,3.2,1.9,2.1,NaN,"M41L, L74LV, M184V, L210W, T215Y"
2,10464,CA10464,200.0,14.0,307,6.4,2.7,NaN,"M41L, E44A, D67N, T69D, M184V, L210W, T215Y"
3,9928,CA9928,200.0,6.7,6.5,1.6,1.4,NaN,"M41L, M184V, T215Y"
4,4372,CA4372,200.0,7.1,0.8,1.3,1.9,NaN,"D67N, K70G, M184V, T215F, K219Q"
5,4391,CA4391,200.0,5.9,1.9,1.3,1.7,NaN,"D67N, K70R, M184V, K219Q"
6,9912,CA9912,200.0,18.0,100,11.0,3.5,NaN,"E40F, M41L, D67N, V75M, M184V, L210W, T215Y, K..."
7,9945,CA9945,200.0,29.0,726,10.0,4.1,NaN,"M41L, D67N, T69D, K70R, V75M, M184V, T215F, K219W"
8,9916,CA9916,200.0,7.7,7.9,2.3,1.8,NaN,"D67N, K70R, M184V, K219Q"
9,9944,CA9944,200.0,8.5,14,1.7,1.7,NaN,"M41L, M184V, L210W, T215Y"
10,3871,CA3871,200.0,8.1,4.7,1.8,1.7,NaN,"M41L, L74V, M184V, L210W, T215Y"
11,10474,CA10474,200.0,8.6,10,1.7,1.9,NaN,"M41L, M184V, T215Y"
12,9919,CA9919,200.0,20.0,228,11.0,20.0,NaN,"A62V, S68G, K70G, V75I, F77L, Y115F, F116Y, Q1..."
13,2633,CA2633,200.0,4.3,3.9,1.4,1.2,NaN,"M41L, M184V, L210W, T215Y"
14,9435,CA9435,200.0,9.6,35,3.3,2.1,NaN,"M41L, E44D, D67N, T69D, M184V, L210W, T215Y"
15,10470,CA10470,4.1,3.5,22,3.2,1.4,NaN,"M41L, E44D, D67N, K70R, L74I, L210W, K219E"
16,10499,CA10499,4.6,6.7,340,3.0,1.8,NaN,"M41L, D67N, K70R, T215Y, K219Q"
17,9949,41731906,200.0,4.8,0.5,0.8,1.5,NaN,M184V
18,10465,CA10465,200.0,7.7,4.4,1.7,1.5,NaN,"M41L, E44D, M184V, L210W, T215Y"
19,9915,CA9915,200.0,9.9,100,3.9,2.1,NaN,"M41L, E44D, D67N, M184V, L210W, T215Y, K219N"
20,11265,SD-5,NaN,4.0,NaN,1.0,NaN,NaN,M184V
21,11251,SD-16,NaN,1.0,NaN,NaN,NaN,NaN,K70R
22,11255,SD-13,NaN,5.0,NaN,NaN,NaN,NaN,"M41L, S68SG, M184V, L210W, T215Y"
23,11247,SD-18,NaN,2.0,NaN,NaN,NaN,NaN,"D67N, K70R, M184V, K219Q"
24,11261,SD-7,NaN,5.0,NaN,NaN,NaN,NaN,"L74V, M184V"
25,11259,SD-10,NaN,3.0,NaN,1.0,NaN,NaN,M184V
26,11243,SD-20,NaN,4.0,NaN,NaN,NaN,NaN,"M41L, M184V, T215Y"
27,11263,SD-6,NaN,4.0,NaN,NaN,NaN,NaN,"D67G, S68G, K70R, M184V, K219Q"
28,11267,SD-2,NaN,7.0,NaN,2.7,NaN,NaN,"M41L, M184V, L210W, T215Y"
29,11253,SD-14,NaN,5.0,NaN,NaN,NaN,NaN,"M41L, L74I, M184V, L210W, T215Y"

In [80]:
# Remove Isolates that lack NRTIDRMs
#df_clean.dropna(subset = ["NRTIDRMs"], inplace= True)
#df_clean

#Replacing isolates that lack NRTIDRMs with empty strings
df_clean["NRTIDRMs"] = df_clean["NRTIDRMs"].fillna("")
df_clean.tail(n = 30)

,IsolateID,IsolateName,3TC,ABC,AZT,D4T,DDI,TDF,NRTIDRMs
2475,743974,DOR-clinical-resistance-7,100.0,2.9,0.5,0.8,1.6,0.8,M184V
2476,692618,ISO3,1.2,0.8,1.7,0.9,0.9,1.2,
2477,692622,ISO7,0.9,1.5,1.5,1.4,1.6,1.8,
2478,692619,ISO4,0.4,0.7,0.3,0.6,0.7,0.3,
2479,743968,DOR-clinical-resistance-1,100.0,2.7,0.1,0.7,1.2,0.5,M184V
2480,743969,DOR-clinical-resistance-2,100.0,3.2,0.1,0.6,1.2,0.6,M184V
2481,692621,ISO6,0.4,0.7,0.8,1.0,0.1,0.8,
2482,743971,DOR-clinical-resistance-4,3.1,0.7,0.2,0.7,1.0,0.3,
2483,692616,ISO1,0.4,1.7,0.3,1.3,1.1,1.5,
2484,743973,DOR-clinical-resistance-6,100.0,2.8,0.1,0.5,1.5,0.4,"K65R, M184V"
2485,743972,DOR-clinical-resistance-5,100.0,3.9,0.2,0.8,1.1,0.4,M184V
2486,743970,DOR-clinical-resistance-3,12.0,2.4,1.0,1.4,1.8,1.6,K65R
2487,692620,ISO5,1.0,0.8,1.4,1.0,0.9,0.9,
2488,692617,ISO2,3.9,0.9,1.9,0.9,1.2,0.7,
2489,63812,CA63812,200.0,9.2,8.9,2.6,2.8,0.8,"M41L, E44D, D67N, T69D, L74V, M184V, L210W, T2..."
2490,48168,CA48168,1.1,0.9,0.6,1.0,1.2,0.8,
2491,38097,CA38097,6.5,4.6,0.4,1.1,6.5,1.0,"M41L, L74V, L210W, T215Y"
2492,41335,CA41335,200.0,7.4,27.0,2.0,2.8,1.5,"M41ML, D67N, K70R, M184V, L210LW, T215F, K219EG"
2493,37679,CA37679,200.0,3.1,0.5,0.6,1.3,0.4,"D67N, M184V, T215C, K219E"
2494,35054,CA35054,1.2,3.3,27.0,2.4,1.1,2.6,"K70R, T215TA"
2495,41303,CA41303,3.9,4.5,190.0,4.0,2.0,4.0,"M41L, D67N, K70R, V75VIM, L210W, T215Y, K219E"
2496,42612,CA42612,7.7,7.8,934.0,8.4,2.9,4.9,"M41L, E44D, D67N, K70R, L74V, L210W, T215Y, K219Q"
2497,42626,CA42626,200.0,2.8,3.4,1.0,1.1,0.8,"M41L, V75M, F77L, M184V, T215FY"
2498,37865,CA37865,200.0,13.0,272.0,5.4,3.6,2.0,"M41L, E44A, T69D, L74V, M184V, L210W, T215Y, K..."
2499,42734,CA42734,10.0,8.6,500.0,6.4,1.7,6.3,"M41L, E44A, T69D, M184MV, L210W, T215Y, K219R"
2500,63964,CA63964,NaN,16.0,657.0,8.2,3.1,3.5,"M41L, E44A, D67N, T69D, V75M, M184V, L210W, T215F"
2501,48124,CA48124,200.0,15.0,500.0,4.3,3.0,5.8,"M41L, E44D, D67N, T69AD, M184MV, L210W, T215Y,..."
2502,761443,MK-8591A-053_ISL_2,NaN,NaN,NaN,NaN,NaN,NaN,"L74I, M184V"
2503,761442,MK-8591A-053_ISL_1,NaN,NaN,NaN,NaN,NaN,NaN,M184I
2504,761440,MK-8591A-053_BIC_1,NaN,NaN,NaN,NaN,NaN,NaN,

In [81]:
#Count Number of Isolates - Number reduced after pruning isolates lacking NRTI-DRMs
df_clean["IsolateID"].nunique()

2505

In [83]:
## Mutation List Generation
df_clean['Mutation_List'] = df_clean['NRTIDRMs'].apply(lambda s: [m.strip() for m in s.split(',') if m.strip()])
df_clean["Mutation_List"].head(n=30)
df_clean["Mutation_List"].tail(n = 30)

2475                                              [M184V]
2476                                                   []
2477                                                   []
2478                                                   []
2479                                              [M184V]
2480                                              [M184V]
2481                                                   []
2482                                                   []
2483                                                   []
2484                                        [K65R, M184V]
2485                                              [M184V]
2486                                               [K65R]
2487                                                   []
2488                                                   []
2489    [M41L, E44D, D67N, T69D, L74V, M184V, L210W, T...
2490                                                   []
2491                           [M41L, L74V, L210W, T215Y]
2492    [M41ML, D67N, K70R, M184V, L210LW, T215F, K219EG]
2493                          [D67N, M184V, T215C, K219E]
2494                                       [K70R, T215TA]
2495      [M41L, D67N, K70R, V75VIM, L210W, T215Y, K219E]
2496    [M41L, E44D, D67N, K70R, L74V, L210W, T215Y, K...
2497                    [M41L, V75M, F77L, M184V, T215FY]
2498    [M41L, E44A, T69D, L74V, M184V, L210W, T215Y, ...
2499      [M41L, E44A, T69D, M184MV, L210W, T215Y, K219R]
2500    [M41L, E44A, D67N, T69D, V75M, M184V, L210W, T...
2501    [M41L, E44D, D67N, T69AD, M184MV, L210W, T215Y...
2502                                        [L74I, M184V]
2503                                              [M184I]
2504                                                   []
Name: Mutation_List, dtype: object

### Calculating Mutation Frequencies

In [84]:
# Preparing for features (Mutations) Matrix generation 
df_clean[["IsolateName","NRTIDRMs", "Mutation_List"]].tail(30)

,IsolateName,NRTIDRMs,Mutation_List
2475,DOR-clinical-resistance-7,M184V,[M184V]
2476,ISO3,,[]
2477,ISO7,,[]
2478,ISO4,,[]
2479,DOR-clinical-resistance-1,M184V,[M184V]
2480,DOR-clinical-resistance-2,M184V,[M184V]
2481,ISO6,,[]
2482,DOR-clinical-resistance-4,,[]
2483,ISO1,,[]
2484,DOR-clinical-resistance-6,"K65R, M184V","[K65R, M184V]"
2485,DOR-clinical-resistance-5,M184V,[M184V]
2486,DOR-clinical-resistance-3,K65R,[K65R]
2487,ISO5,,[]
2488,ISO2,,[]
2489,CA63812,"M41L, E44D, D67N, T69D, L74V, M184V, L210W, T2...","[M41L, E44D, D67N, T69D, L74V, M184V, L210W, T..."
2490,CA48168,,[]
2491,CA38097,"M41L, L74V, L210W, T215Y","[M41L, L74V, L210W, T215Y]"
2492,CA41335,"M41ML, D67N, K70R, M184V, L210LW, T215F, K219EG","[M41ML, D67N, K70R, M184V, L210LW, T215F, K219EG]"
2493,CA37679,"D67N, M184V, T215C, K219E","[D67N, M184V, T215C, K219E]"
2494,CA35054,"K70R, T215TA","[K70R, T215TA]"
2495,CA41303,"M41L, D67N, K70R, V75VIM, L210W, T215Y, K219E","[M41L, D67N, K70R, V75VIM, L210W, T215Y, K219E]"
2496,CA42612,"M41L, E44D, D67N, K70R, L74V, L210W, T215Y, K219Q","[M41L, E44D, D67N, K70R, L74V, L210W, T215Y, K..."
2497,CA42626,"M41L, V75M, F77L, M184V, T215FY","[M41L, V75M, F77L, M184V, T215FY]"
2498,CA37865,"M41L, E44A, T69D, L74V, M184V, L210W, T215Y, K...","[M41L, E44A, T69D, L74V, M184V, L210W, T215Y, ..."
2499,CA42734,"M41L, E44A, T69D, M184MV, L210W, T215Y, K219R","[M41L, E44A, T69D, M184MV, L210W, T215Y, K219R]"
2500,CA63964,"M41L, E44A, D67N, T69D, V75M, M184V, L210W, T215F","[M41L, E44A, D67N, T69D, V75M, M184V, L210W, T..."
2501,CA48124,"M41L, E44D, D67N, T69AD, M184MV, L210W, T215Y,...","[M41L, E44D, D67N, T69AD, M184MV, L210W, T215Y..."
2502,MK-8591A-053_ISL_2,"L74I, M184V","[L74I, M184V]"
2503,MK-8591A-053_ISL_1,M184I,[M184I]
2504,MK-8591A-053_BIC_1,,[]

### Feature Matrix Generation

In [93]:
# Mutation frequency calculation
#Expanding comma-separated mutations into separate rows (Long Format)
df_mut_exploded = df_clean.explode('Mutation_List').dropna(subset=['Mutation_List'])
df_mut_exploded.head()

#Mutation Frequency Analysis
total_isolates = df_clean['IsolateID'].nunique()
global_frequencies = df_mut_exploded['Mutation_List'].value_counts().reset_index()
global_frequencies = global_frequencies[
    (global_frequencies['Mutation_List'] != "") 
]
global_frequencies.columns = ['Mutation_List', 'Absolute_Count']

global_frequencies. head(n = 30)
#print(total_isolates)

   Mutation_List  Absolute_Count
0          M184V            1153
1           M41L             999
2          T215Y             887
3           D67N             811
4          L210W             697
5           K70R             474
6          K219Q             364
7          T215F             259
8           T69D             241
9           E44D             211
10          L74V             192
11          S68G             176
12         K219E             159
13          L74I             103
14          V75M              91
15        M184MV              82
16          A62V              80
17          K65R              77
18         K219N              76
19         K219R              75
20          D67G              70
21         Q151M              63
22          V75I              61
23         D67DN              59
24          E44A              54
25         M41ML              52
26         Y115F              51
27          F77L              49
28        L210LW              49
29         K70KR              48

In [94]:
#Check dimensionality
df_clean.columns

#Check empty
mut_empty = (df_clean["Mutation_List"].str.len() == 0).sum()
mut_empty

512

total_isolate

In [95]:
#Calculate proportionality of mutations
global_frequencies['Global_Frequency_%'] = (global_frequencies['Absolute_Count'] / (total_isolates - mut_empty))* 100
global_frequencies.head(30)

   Mutation_List  Absolute_Count  Global_Frequency_%
0          M184V            1153           57.852484
1           M41L             999           50.125439
2          T215Y             887           44.505770
3           D67N             811           40.692423
4          L210W             697           34.972403
5           K70R             474           23.783241
6          K219Q             364           18.263924
7          T215F             259           12.995484
8           T69D             241           12.092323
9           E44D             211           10.587055
10          L74V             192            9.633718
11          S68G             176            8.830908
12         K219E             159            7.977923
13          L74I             103            5.168088
14          V75M              91            4.565981
15        M184MV              82            4.114400
16          A62V              80            4.014049
17          K65R              77            3.863522
18         K219N              76            3.813347
19         K219R              75            3.763171
20          D67G              70            3.512293
21         Q151M              63            3.161064
22          V75I              61            3.060712
23         D67DN              59            2.960361
24          E44A              54            2.709483
25         M41ML              52            2.609132
26         Y115F              51            2.558956
27          F77L              49            2.458605
28        L210LW              49            2.458605
29         K70KR              48            2.408430

In [ ]:
# Filter based on mutation frequency (< 0.4)
retained_mutations = global_frequencies[global_frequencies["Global_Frequency_%"] >= 1.0]
retained_mutations.head()
retained_mutations.tail()

   Mutation_List  Absolute_Count  Global_Frequency_%
37         A62AV              27            1.354742
38        K219KR              27            1.354742
39        K219KN              26            1.304566
40         T215D              23            1.154039
41          K70G              22            1.103864

In [97]:
retained_mutations.shape

(42, 3)

## Subsetting data

In [98]:
#Data - df_clean
df_clean.head(n=30)

,IsolateID,IsolateName,3TC,ABC,AZT,D4T,DDI,TDF,NRTIDRMs,Mutation_List
0,9918,CA9918,200.0,4.6,0.6,1.0,1.6,NaN,M184V,[M184V]
1,3832,CA3832,200.0,8.8,3.2,1.9,2.1,NaN,"M41L, L74LV, M184V, L210W, T215Y","[M41L, L74LV, M184V, L210W, T215Y]"
2,10464,CA10464,200.0,14.0,307,6.4,2.7,NaN,"M41L, E44A, D67N, T69D, M184V, L210W, T215Y","[M41L, E44A, D67N, T69D, M184V, L210W, T215Y]"
3,9928,CA9928,200.0,6.7,6.5,1.6,1.4,NaN,"M41L, M184V, T215Y","[M41L, M184V, T215Y]"
4,4372,CA4372,200.0,7.1,0.8,1.3,1.9,NaN,"D67N, K70G, M184V, T215F, K219Q","[D67N, K70G, M184V, T215F, K219Q]"
5,4391,CA4391,200.0,5.9,1.9,1.3,1.7,NaN,"D67N, K70R, M184V, K219Q","[D67N, K70R, M184V, K219Q]"
6,9912,CA9912,200.0,18.0,100,11.0,3.5,NaN,"E40F, M41L, D67N, V75M, M184V, L210W, T215Y, K...","[E40F, M41L, D67N, V75M, M184V, L210W, T215Y, ..."
7,9945,CA9945,200.0,29.0,726,10.0,4.1,NaN,"M41L, D67N, T69D, K70R, V75M, M184V, T215F, K219W","[M41L, D67N, T69D, K70R, V75M, M184V, T215F, K..."
8,9916,CA9916,200.0,7.7,7.9,2.3,1.8,NaN,"D67N, K70R, M184V, K219Q","[D67N, K70R, M184V, K219Q]"
9,9944,CA9944,200.0,8.5,14,1.7,1.7,NaN,"M41L, M184V, L210W, T215Y","[M41L, M184V, L210W, T215Y]"
10,3871,CA3871,200.0,8.1,4.7,1.8,1.7,NaN,"M41L, L74V, M184V, L210W, T215Y","[M41L, L74V, M184V, L210W, T215Y]"
11,10474,CA10474,200.0,8.6,10,1.7,1.9,NaN,"M41L, M184V, T215Y","[M41L, M184V, T215Y]"
12,9919,CA9919,200.0,20.0,228,11.0,20.0,NaN,"A62V, S68G, K70G, V75I, F77L, Y115F, F116Y, Q1...","[A62V, S68G, K70G, V75I, F77L, Y115F, F116Y, Q..."
13,2633,CA2633,200.0,4.3,3.9,1.4,1.2,NaN,"M41L, M184V, L210W, T215Y","[M41L, M184V, L210W, T215Y]"
14,9435,CA9435,200.0,9.6,35,3.3,2.1,NaN,"M41L, E44D, D67N, T69D, M184V, L210W, T215Y","[M41L, E44D, D67N, T69D, M184V, L210W, T215Y]"
15,10470,CA10470,4.1,3.5,22,3.2,1.4,NaN,"M41L, E44D, D67N, K70R, L74I, L210W, K219E","[M41L, E44D, D67N, K70R, L74I, L210W, K219E]"
16,10499,CA10499,4.6,6.7,340,3.0,1.8,NaN,"M41L, D67N, K70R, T215Y, K219Q","[M41L, D67N, K70R, T215Y, K219Q]"
17,9949,41731906,200.0,4.8,0.5,0.8,1.5,NaN,M184V,[M184V]
18,10465,CA10465,200.0,7.7,4.4,1.7,1.5,NaN,"M41L, E44D, M184V, L210W, T215Y","[M41L, E44D, M184V, L210W, T215Y]"
19,9915,CA9915,200.0,9.9,100,3.9,2.1,NaN,"M41L, E44D, D67N, M184V, L210W, T215Y, K219N","[M41L, E44D, D67N, M184V, L210W, T215Y, K219N]"
20,11265,SD-5,NaN,4.0,NaN,1.0,NaN,NaN,M184V,[M184V]
21,11251,SD-16,NaN,1.0,NaN,NaN,NaN,NaN,K70R,[K70R]
22,11255,SD-13,NaN,5.0,NaN,NaN,NaN,NaN,"M41L, S68SG, M184V, L210W, T215Y","[M41L, S68SG, M184V, L210W, T215Y]"
23,11247,SD-18,NaN,2.0,NaN,NaN,NaN,NaN,"D67N, K70R, M184V, K219Q","[D67N, K70R, M184V, K219Q]"
24,11261,SD-7,NaN,5.0,NaN,NaN,NaN,NaN,"L74V, M184V","[L74V, M184V]"
25,11259,SD-10,NaN,3.0,NaN,1.0,NaN,NaN,M184V,[M184V]
26,11243,SD-20,NaN,4.0,NaN,NaN,NaN,NaN,"M41L, M184V, T215Y","[M41L, M184V, T215Y]"
27,11263,SD-6,NaN,4.0,NaN,NaN,NaN,NaN,"D67G, S68G, K70R, M184V, K219Q","[D67G, S68G, K70R, M184V, K219Q]"
28,11267,SD-2,NaN,7.0,NaN,2.7,NaN,NaN,"M41L, M184V, L210W, T215Y","[M41L, M184V, L210W, T215Y]"
29,11253,SD-14,NaN,5.0,NaN,NaN,NaN,NaN,"M41L, L74I, M184V, L210W, T215Y","[M41L, L74I, M184V, L210W, T215Y]"

In [101]:
# Fix AZT fold change values, currently object (str) ---> float
df_clean["AZT"] = (df_clean["AZT"].astype(str).str.replace(",","", regex = False).replace ('nan', pd.NA))
df_clean["AZT"] = pd.to_numeric(df_clean["AZT"], errors = "coerce")

df_clean["AZT"].dtypes

dtype('float64')

In [102]:
# Drug Thresholds 
DRUGS = {
    '3TC' : 3.5,
    'ABC' : 4.5,
    'AZT' : 1.9,
    'D4T' : 1.7,
    'DDI' : 1.3,
    'TDF' : 1.4
}

In [103]:
df_clean.columns

Index(['IsolateID', 'IsolateName', '3TC', 'ABC', 'AZT', 'D4T', 'DDI', 'TDF',
       'NRTIDRMs', 'Mutation_List'],
      dtype='str')

In [106]:
#### 3TC subsetting
print("Lamivudine (3TC) subsetting .....")

df_3TC = (df_clean[['IsolateID','NRTIDRMs', '3TC']].rename(columns = {'3TC' : "FoldChange"}).dropna(subset = ["FoldChange"]).reset_index(drop = True))
df_3TC["resistance"] = (df_3TC["FoldChange"]>= 3.5).astype(int)
df_3TC.head()

Lamivudine (3TC) subsetting .....

,IsolateID,NRTIDRMs,FoldChange,resistance
0,9918,M184V,200.0,1
1,3832,"M41L, L74LV, M184V, L210W, T215Y",200.0,1
2,10464,"M41L, E44A, D67N, T69D, M184V, L210W, T215Y",200.0,1
3,9928,"M41L, M184V, T215Y",200.0,1
4,4372,"D67N, K70G, M184V, T215F, K219Q",200.0,1

In [ ]:
# ## Create the feature matrix (X) - One Hot encoding of the 'Mutation_List

# from sklearn.preprocessing import MultiLabelBinarizer

# #Create multilabelBinarizer object
# mlb = MultiLabelBinarizer()

# # One-Hot encode ["Mutation_List"]
# X = mlb.transform(df_clean["Mutation_List"])

# X = pd.DataFrame(X, columns= mlb.classes_, index=df_clean["IsolateID"])

# X.head(n=30)

,,A62AV,A62V,D67DEG,D67DG,D67DH,D67DN,D67E,D67EK,D67G,...,V75M,V75MT,V75S,V75T,V75VA,V75VI,V75VIM,V75VM,Y115F,Y115YF
IsolateID,,,,,,,,,,,,,,,,,,,,,
9918,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3832,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10464,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9928,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4372,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4391,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9912,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
9945,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
9916,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9944,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3871,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10474,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9919,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2633,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9435,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10470,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9949,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10465,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9915,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11265,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11251,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11255,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11247,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11261,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11259,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11243,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11263,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
11267,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11253,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# # Explore Feature Matrix (X)
# print(X.shape)

(2505, 166)

In [ ]:
# #Inspect feature name (Make sure they are Mutations)
# X.columns.tolist()[:20]

['',
 'A62AV',
 'A62V',
 'D67DEG',
 'D67DG',
 'D67DH',
 'D67DN',
 'D67E',
 'D67EK',
 'D67G',
 'D67GS',
 'D67GV',
 'D67H',
 'D67HN',
 'D67N',
 'D67NH',
 'D67NS',
 'D67NT',
 'D67S',
 'D67~']

### Target Matrix Generation

In [ ]:
# df_target = pd.read_csv("geno-pheno_clean.tsv",sep = "\t")
# df_target.head(n = 30)
# df_target['Drug_List'] = df_target['Drugs'].apply(lambda s: [d.strip() for d in s.split(',') if d.strip()])

KeyError: 'Drugs'

In [ ]:
# Create y - dataframe
# df_target = df_clean[["IsolateID","3TC","ABC","AZT","D4T","DDI","TDF"]]
# y.head(n = 30)

KeyError: 'drugs'

In [ ]:
# Countercheck Isolate_Name compatibility between X and y

# X = X.loc[y.index]

NameError: name 'y' is not defined